# Generated by Django 2.0.3 on 2018-04-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('post', models.FileField(upload_to='')),
                ('post_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('profile_picture', models.FileField(upload_to='')),
                ('Location', models.CharField(max_length=250)),
                ('links', models.CharField(max_length=250)),
                ('contacts', models.CharField(max_length=250)),
                ('charges', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='pictures',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Explore.Users'),
        ),
    ]
